apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscale-script
data:
  {{- $files := .Files }}
  {{- range tuple "server.py" "client.py" "cpuload.php" "memload.php"}}
  {{ . }}: |-
    {{- $files.Get . | nindent 4}}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscale-apacheconf
  labels:
    app: autoscale-server
data:
  "ports.conf": |
    # Empty ports.conf
    # Listen statements are in the sites conf files.

  "000-default.conf": |
    Listen 5122
    <VirtualHost *:5122>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>
    
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: autoscale-apacheconf
#   labels:
#     app: autoscale-server
# data:
#   "000-default.conf": |
#     Listen 5122
#     <VirtualHost *:5122>
#         ServerAdmin webmaster@localhost
#         DocumentRoot /var/www/html
#         ErrorLog ${APACHE_LOG_DIR}/error.log
#         CustomLog ${APACHE_LOG_DIR}/access.log combined
#     </VirtualHost>

