apiVersion: v1
kind: Service
metadata:
  name: {{ include "visual.fullname" . }}
  labels:
    {{- include "visual.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: grafana
  selector:
    {{- include "visual.selectorLabels" . | nindent 4 }}
