kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
        listen       8080;
        server_name  localhost;

        access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /config/ {
            root /;
        }

        error_page  404              /404.html;


        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location ~ \.load$ {
            root           html;
            fastcgi_pass   127.0.0.1:8081;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
            include        fastcgi_params;
        }

    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hpa-server
  labels:
    app:  hpa-server
spec:
  selector:
    matchLabels:
      app: hpa-server
  replicas: 1
  template:
    metadata:
      labels:
        app:  hpa-server
    spec:
      containers:
      - name:  nginx
        image:  nginx:latest
        ports:
        - containerPort:  8080
          name:  nginx-port
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        resources:
          limits:
            cpu: 1500m
            memory: 1024Mi
          requests:
            cpu: 1000m
            memory: 512Mi
      - name: fastcgi
        image: docker.io/qdai/fastcgi:v1.0
        imagePullPolicy: Always
        command: ["spawn-fcgi", "-n", "-a", "127.0.0.1", "-p", "8081", "app.fcgi"]
        ports:
        - containerPort:  8081
          name:  fastcgi-port
        resources:
          limits:
            cpu: 1500m
            memory: 1024Mi
          requests:
            cpu: 1000m
            memory: 512Mi
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: default.conf

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: hpa-svc
spec:
  selector:
    app: hpa-server
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
